global:
  scrape_interval: 5s
  evaluation_interval: 5s
  external_labels:
    monitor: 'monitoring-lab'

scrape_configs:
  - job_name: 'go-app'
    static_configs:
      - targets: ['go-app:8080']
        labels:
          app: 'go-app'
          service: 'go-application'

  - job_name: 'spring-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['spring-app:8081']
        labels:
          app: 'spring-app'
          service: 'spring-application'

  - job_name: 'mongodb-exporter'
    static_configs:
      - targets: ['mongodb-exporter:9216']
        labels:
          app: 'mongodb'
          service: 'mongodb-exporter'

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
        labels:
          app: 'host'
          service: 'node-exporter'

